#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  appDomain: "SET_BY_TERRAFORM"
  basicAuthPassword: "SET_BY_TERRAFORM"
global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingressRoute.adminDomain: "apps.{{.Values.projectValues.appDomain}}"
      ingressRoute.host: "apps.{{.Values.projectValues.appDomain}}"
      ingressRoute.appDomain: "{{.Values.projectValues.appDomain}}"
charts:
  # Override values with local values file
  iits-admin-dashboard:
    namespace: apps
    targetRevision: 1.3.0
    # values files needs to be inside this chart
    valueFile: "value-files/admin-dashboard/values.yaml"
    parameters:
      deployment.replicaCount: "1"
  prometheus-stack:
    namespace: monitoring
    repoURL: "https://charts.iits.tech"
    targetRevision: "43.2.0"
    ignoreDifferences:
      - jsonPointers:
          - /imagePullSecrets
        kind: ServiceAccount
    syncOptions:
      - ServerSideApply=true
    parameters:
      global.alertmanager.host: "apps.{{.Values.projectValues.appDomain}}"
      global.prometheus.host: "apps.{{.Values.projectValues.appDomain}}"
      global.grafana.host: "apps.{{.Values.projectValues.appDomain}}"
      prometheusStack.grafana.adminPassword: "{{.Values.projectValues.basicAuthPassword}}"