#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  appDomain: "SET_BY_TERRAFORM"
  basicAuthPassword: "SET_BY_TERRAFORM"
global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingressRoute.adminDomain: "apps.{{.Values.projectValues.appDomain}}"
      ingressRoute.host: "apps.{{.Values.projectValues.appDomain}}"
      ingressRoute.appDomain: "{{.Values.projectValues.appDomain}}"
charts:
  # Remote chart from public helm repo
  bitnami-minio:
    namespace: bitnami-minio # Which namespace should the service be deployed
    repoURL: "https://charts.bitnami.com/bitnami" # Helm repo URL by default it takes the helm repo URL from line 11
    chart: minio # Name of the chart
    targetRevision: 14.1.0
